export const RESET_STATE = "RESET_STATE_EMPLOYMENT_RELATIONSHIP";
export const GET_LIST = "GET_LIST_EMPLOYMENT_RELATIONSHIP";
export const GET_LIST_LOADING = "GET_LIST_LOADING_EMPLOYMENT_RELATIONSHIP";
export const GET_LIST_ERROR = "GET_LIST_ERROR_EMPLOYMENT_RELATIONSHIP";
