export const RESET_STATE = "RESET_STATE_EVALUATION_SCALE";
export const GET_LIST = "GET_LIST_EVALUATION_SCALE";
export const GET_LIST_LOADING = "GET_LIST_LOADING_EVALUATION_SCALE";
export const GET_LIST_ERROR = "GET_LIST_ERROR_EVALUATION_SCALE";
