export const RESET_STATE = "RESET_STATE_SPIDER_CHART_ATTRITION";
export const GET_LIST = "GET_LIST_SPIDER_CHART_ATTRITION";
export const GET_LIST_LOADING = "GET_LIST_LOADING_SPIDER_CHART_ATTRITION";
export const GET_LIST_ERROR = "GET_LIST_ERROR_SPIDER_CHART_ATTRITION";
