export const RESET_STATE = "RESET_STATE_AGREEMENT_STATES";
export const GET_LIST = "GET_LIST_AGREEMENT_STATES";
export const GET_LIST_LOADING = "GET_LIST_LOADING_AGREEMENT_STATES";
export const GET_LIST_ERROR = "GET_LIST_ERROR_AGREEMENT_STATES";
