export const RESET_STATE = "RESET_STATE_POTENTIAL";
export const GET_LIST = "GET_LIST_POTENTIAL";
export const GET_LIST_LOADING = "GET_LIST_LOADING_POTENTIAL";
export const GET_LIST_ERROR = "GET_LIST_ERROR_POTENTIAL";
