export const RESET_STATE = "RESET_STATE_INFO_TYPES";
export const GET_LIST = "GET_LIST_INFO_TYPES";
export const GET_LIST_LOADING = "GET_LIST_LOADING_INFO_TYPES";
export const GET_LIST_ERROR = "GET_LIST_ERROR_INFO_TYPES";
export const RESET_STATE_POST_INFO = "RESET_STATE_POST_INFO";
export const POST_INFO_LOADING = "POST_INFO_LOADING";
export const POST_INFO = "POST_INFO";
export const POST_INFO_ERROR = "POST_INFO_ERROR";
