export const RESET_STATE = "RESET_STATE_POSITION";
export const GET_LIST = "GET_LIST_POSITION";
export const GET_LIST_LOADING = "GET_LIST_LOADING_POSITION";
export const GET_LIST_ERROR = "GET_LIST_ERROR_POSITION";

export const RESET_PROCESS_POSITION = "RESET_PROCESS_POSITION";
export const PROCESS_POSITION = "PROCESS_POSITION";
export const PROCESS_POSITION_LOADING = "PROCESS_POSITION_LOADING";
export const PROCESS_POSITION_ERROR = "PROCESS_POSITION_ERROR";
