export const RESET_STATE = "RESET_STATE_NINE_BOX";
export const GET_LIST = "GET_LIST_NINE_BOX";
export const GET_LIST_LOADING = "GET_LIST_LOADING_NINE_BOX";
export const GET_LIST_ERROR = "GET_LIST_ERROR_NINE_BOX";
export const GET_NINEBOX_RESULTS = "GET_NINEBOX_RESULTS";
export const GET_NINEBOX_RESULTS_LOADING = "GET_NINEBOX_RESULTS_LOADING";
export const GET_NINEBOX_RESULTS_ERROR = "GET_NINEBOX_RESULTS_ERROR";
export const RESET_STATE_NINEBOX_RESULT = "RESET_STATE_NINEBOX_RESULT";
