export const RESET_STATE = "RESET_STATE_TIME_OFF_CATEGORIES";
export const GET_LIST = "GET_LIST_TIME_OFF_CATEGORIES";
export const GET_LIST_LOADING = "GET_LIST_LOADING_TIME_OFF_CATEGORIES";
export const GET_LIST_ERROR = "GET_LIST_ERROR_TIME_OFF_CATEGORIES";
