export const RESET_STATE = "RESET_STATE_MANAGERS";
export const GET_LIST = "GET_LIST_MANAGERS";
export const GET_LIST_LOADING = "GET_LIST_LOADING_MANAGERS";
export const GET_LIST_ERROR = "GET_LIST_ERROR_MANAGERS";
