export const RESET_STATE = "RESET_STATE_CURRENCIES";
export const GET_LIST = "GET_LIST_CURRENCIES";
export const GET_LIST_LOADING = "GET_LIST_LOADING_CURRENCIES";
export const GET_LIST_ERROR = "GET_LIST_ERROR_CURRENCIES";
