export const RESET_STATE = "RESET_STATE_LEGAL_ENTITY";
export const GET_LIST = "GET_LIST_LEGAL_ENTITY";
export const GET_LIST_LOADING = "GET_LIST_LOADING_LEGAL_ENTITY";
export const GET_LIST_ERROR = "GET_LIST_ERROR_LEGAL_ENTITY";

export const RESET_PROCESS_LEGAL_ENTITY = "RESET_PROCESS_LEGAL_ENTITY";
export const PROCESS_LEGAL_ENTITY = "PROCESS_LEGAL_ENTITY";
export const PROCESS_LEGAL_ENTITY_LOADING = "PROCESS_LEGAL_ENTITY_LOADING";
export const PROCESS_LEGAL_ENTITY_ERROR = "PROCESS_LEGAL_ENTITY_ERROR";
