export const RESET_STATE = "RESET_STATE_CITIES";
export const GET_LIST = "GET_LIST_CITIES";
export const GET_LIST_LOADING = "GET_LIST_LOADING_CITIES";
export const GET_LIST_ERROR = "GET_LIST_ERROR_CITIES";

export const RESET_PROCESS_CITY = "RESET_PROCESS_CITY";
export const PROCESS_CITY = "PROCESS_CITY";
export const PROCESS_CITY_LOADING = "PROCESS_CITY_LOADING";
export const PROCESS_CITY_ERROR = "PROCESS_CITY_ERROR";
