export const RESET_STATE = "RESET_STATE_SIGN_IN";
export const GET_ONE = "GET_ONE_SIGN_IN";
export const GET_ONE_LOADING = "GET_ONE_LOADING_SIGN_IN";
export const GET_ONE_ERROR = "GET_ONE_ERROR_SIGN_IN";
