export const RESET_STATE = "RESET_STATE_DOCUMENTS";
export const GET_LIST = "GET_LIST_COLLABORATOR_DOCUMENTS";
export const GET_LIST_LOADING = "GET_LIST_LOADING_COLLABORATOR_DOCUMENTS";
export const GET_LIST_ERROR = "GET_LIST_ERROR_COLLABORATOR_DOCUMENTS";

export const RESET_STATE_PROCESS_DOCUMENT = "RESET_STATE_PROCESS_DOCUMENTS";
export const PROCESS_DOCUMENT = "PROCESS_COLLABORATOR_DOCUMENTS";
export const PROCESS_DOCUMENT_LOADING = "PROCESS_COLLABORATOR_DOCUMENTS_LOADING";
export const PROCESS_DOCUMENT_ERROR = "PROCESS_COLLABORATOR_DOCUMENTS_ERROR";
