export const RESET_STATE = "RESET_STATE_TYPE_OF_CONTRACT";
export const GET_LIST = "GET_LIST_TYPE_OF_CONTRACT";
export const GET_LIST_LOADING = "GET_LIST_LOADING_TYPE_OF_CONTRACT";
export const GET_LIST_ERROR = "GET_LIST_ERROR_TYPE_OF_CONTRACT";

export const RESET_STATE_CONTRACT_TYPE = "RESET_STATE_CONTRACT_TYPE";
export const PROCCESS_CONTRACT_TYPE = "PROCCESS_CONTRACT_TYPE";
export const PROCCESS_CONTRACT_TYPE_LOADING = "PROCCESS_CONTRACT_TYPE_LOADING";
export const PROCCESS_CONTRACT_TYPE_ERROR = "PROCCESS_CONTRACT_TYPE_ERROR";
