export const RESET_STATE = "RESET_STATE_STATES";
export const GET_LIST = "GET_LIST_STATES";
export const GET_LIST_LOADING = "GET_LIST_LOADING_STATES";
export const GET_LIST_ERROR = "GET_LIST_ERROR_STATES";
