export const RESET_STATE = "RESET_STATE_BENEFITS";
export const GET_LIST = "GET_LIST_BENEFITS";
export const GET_LIST_LOADING = "GET_LIST_LOADING_BENEFITS";
export const GET_LIST_ERROR = "GET_LIST_ERROR_BENEFITS";
export const RESET_STATE_ONE = "RESET_STATE_ONE_BENEFIT";
export const GET_ONE = "GET_ONE_BENEFIT";
export const GET_ONE_LOADING = "GET_ONE_LOADING_BENEFIT";
export const GET_ONE_ERROR = "GET_ONE_ERROR_BENEFIT";
