export const RESET_STATE = "RESET_STATE_FOLLOW_UP";
export const GET_LIST = "GET_LIST_FOLLOW_UP";
export const GET_LIST_LOADING = "GET_LIST_LOADING_FOLLOW_UP";
export const GET_LIST_ERROR = "GET_LIST_ERROR_FOLLOW_UP";
