export const RESET_STATE = "RESET_STATE_PERFORMANCE_GOOD_LEADER";
export const GET_LIST = "GET_LIST_PERFORMANCE_GOOD_LEADER";
export const GET_LIST_LOADING = "GET_LIST_LOADING_PERFORMANCE_GOOD_LEADER";
export const GET_LIST_ERROR = "GET_LIST_ERROR_PERFORMANCE_GOOD_LEADER";

export const RESET_STATE_TOP = "RESET_STATE_TOP_PERFORMANCE_GOOD_LEADER";
export const GET_TOP_LIST = "GET_TOP_LIST_PERFORMANCE_GOOD_LEADER";
export const GET_TOP_LIST_LOADING = "GET_TOP_LIST_LOADING_PERFORMANCE_GOOD_LEADER";
export const GET_TOP_LIST_ERROR = "GET_TOP_LIST_ERROR_PERFORMANCE_GOOD_LEADER";

export const RESET_STATE_BOTTOM = "RESET_STATE_BOTTOM_PERFORMANCE_GOOD_LEADER";
export const GET_BOTTOM_LIST = "GET_BOTTOM_LIST_PERFORMANCE_GOOD_LEADER";
export const GET_BOTTOM_LIST_LOADING = "GET_BOTTOM_LIST_LOADING_PERFORMANCE_GOOD_LEADER";
export const GET_BOTTOM_LIST_ERROR = "GET_BOTTOM_LIST_ERROR_PERFORMANCE_GOOD_LEADER";

export const RESET_STATE_SURVEY_RESULTS = "RESET_STATE_SURVEY_RESULTS_PERFORMANCE_GOOD_LEADER";
export const GET_SURVEY_RESULTS_LIST_LOADING = "GET_SURVEY_RESULTS_LIST_LOADING_PERFORMANCE_GOOD_LEADER";
export const GET_SURVEY_RESULTS_LIST_ERROR = "GET_SURVEY_RESULTS_LIST_ERROR_PERFORMANCE_GOOD_LEADER";
export const GET_SURVEY_RESULTS_LIST = "GET_SURVEY_RESULTS_LIST_PERFORMANCE_GOOD_LEADER";
