export const RESET_STATE = "RESET_STATE_PERFORMANCE_HEAT_MAP";
export const GET_LIST = "GET_LIST_PERFORMANCE_HEAT_MAP";
export const GET_LIST_LOADING = "GET_LIST_LOADING_PERFORMANCE_HEAT_MAP";
export const GET_LIST_ERROR = "GET_LIST_ERROR_PERFORMANCE_HEAT_MAP";
