export const RESET_STATE = "RESET_STATE_PERFORMANCE";
export const GET_LIST = "GET_LIST_PERFORMANCE";
export const GET_LIST_LOADING = "GET_LIST_LOADING_PERFORMANCE";
export const GET_LIST_ERROR = "GET_LIST_ERROR_PERFORMANCE";
