export const RESET_STATE_TOP = "RESET_STATE_TOP_PERFORMANCE_RANKING";
export const GET_TOP_RANKING = "GET_TOP_RANKING_PERFORMANCE";
export const GET_TOP_RANKING_LOADING = "GET_TOP_RANKING_LOADING_PERFORMANCE";
export const GET_TOP_RANKING_ERROR = "GET_TOP_RANKING_ERROR_PERFORMANCE";

export const RESET_STATE_BOTTOM = "RESET_STATE_BOTTOM_PERFORMANCE_RANKING";
export const GET_BOTTOM_RANKING = "GET_BOTTOM_RANKING_PERFORMANCE";
export const GET_BOTTOM_RANKING_LOADING = "GET_BOTTOM_RANKING_LOADING_PERFORMANCE";
export const GET_BOTTOM_RANKING_ERROR = "GET_BOTTOM_RANKING_ERROR_PERFORMANCE";