export const RESET_STATE = "RESET_STATE_PERFORMANCE_SURVEY_RESULTS";
export const GET_LIST = "GET_LIST_PERFORMANCE_SURVEY_RESULTS";
export const GET_LIST_LOADING = "GET_LIST_LOADING_PERFORMANCE_SURVEY_RESULTS";
export const GET_LIST_ERROR = "GET_LIST_ERROR_PERFORMANCE_SURVEY_RESULTS";

export const RESET_STATE_ONE = "RESET_STATE_ONE_PERFORMANCE_SURVEY_RESULTS";
export const GET_ONE = "GET_ONE_PERFORMANCE_SURVEY_RESULTS";
export const GET_ONE_LOADING = "GET_ONE_LOADING_PERFORMANCE_SURVEY_RESULTS";
export const GET_ONE_ERROR = "GET_ONE_ERROR_PERFORMANCE_SURVEY_RESULTS";
