export const RESET_STATE = "RESET_STATE_COLLABORATOR_ATTRITION";
export const GET_LIST = "GET_LIST_COLLABORATOR_ATTRITION";
export const GET_LIST_LOADING = "GET_LIST_LOADING_COLLABORATOR_ATTRITION";
export const GET_LIST_ERROR = "GET_LIST_ERROR_COLLABORATOR_ATTRITION";
