export const RESET_STATE = "RESET_STATE_PERSONALITIES";
export const GET_LIST = "GET_LIST_PERSONALITIES";
export const GET_LIST_LOADING = "GET_LIST_LOADING_PERSONALITIES";
export const GET_LIST_ERROR = "GET_LIST_ERROR_PERSONALITIES";
