export const RESET_STATE = "RESET_STATE_AGREEMENT_CATEGORIES";
export const GET_LIST = "GET_LIST_AGREEMENT_CATEGORIES";
export const GET_LIST_LOADING = "GET_LIST_LOADING_AGREEMENT_CATEGORIES";
export const GET_LIST_ERROR = "GET_LIST_ERROR_AGREEMENT_CATEGORIES";

export const RESET_PROCESS_AGREEMENT_CATEGORIES = "RESET_PROCESS_AGREEMENT_CATEGORIES";
export const PROCESS_AGREEMENT_CATEGORIES = "PROCESS_AGREEMENT_CATEGORIES";
export const PROCESS_AGREEMENT_CATEGORIES_LOADING = "PROCESS_AGREEMENT_CATEGORIES_LOADING";
export const PROCESS_AGREEMENT_CATEGORIES_ERROR = "PROCESS_AGREEMENT_CATEGORIES_ERROR";
