export const RESET_STATE = "RESET_STATE_ORG_UNITS";
export const GET_LIST = "GET_LIST_ORG_UNITS";
export const GET_LIST_LOADING = "GET_LIST_LOADING_ORG_UNITS";
export const GET_LIST_ERROR = "GET_LIST_ERROR_ORG_UNITS";

export const RESET_STATE_TREE = "RESET_STATE_ORG_UNITS_TREE";
export const GET_LIST_TREE = "GET_LIST_ORG_UNITS_TREE";
export const GET_LIST_TREE_LOADING = "GET_LIST_LOADING_ORG_UNITS_TREE";
export const GET_LIST_TREE_ERROR = "GET_LIST_ERROR_ORG_UNITS_TREE";

export const RESET_STATE_PROCESS = "RESET_STATE_ORG_UNITS_PROCESS";
export const PROCESS_ORG_UNITS = "PROCESS_ORG_UNITS";
export const PROCESS_ORG_UNITS_LOADING = "PROCESS_ORG_UNITS_LOADING";
export const PROCESS_ORG_UNITS_ERROR = "PROCESS_ORG_UNITS_ERROR";
