export const RESET_STATE = "RESET_STATE_ORG_UNITS_TYPES";
export const GET_LIST = "GET_LIST_ORG_UNITS_TYPES";
export const GET_LIST_LOADING = "GET_LIST_LOADING_ORG_UNITS_TYPES";
export const GET_LIST_ERROR = "GET_LIST_ERROR_ORG_UNITS_TYPES";
