export const RESET_STATE = "RESET_STATE_DYNAMIC_ATTRIBUTE";
export const GET_LIST = "GET_LIST_DYNAMIC_ATTRIBUTE";
export const GET_LIST_LOADING = "GET_LIST_LOADING_DYNAMIC_ATTRIBUTE";
export const GET_LIST_ERROR = "GET_LIST_ERROR_DYNAMIC_ATTRIBUTE";

export const RESET_PROCESS_DYNAMIC_ATTRIBUTE = "RESET_PROCESS_DYNAMIC_ATTRIBUTE";
export const PROCESS_DYNAMIC_ATTRIBUTE = "PROCESS_DYNAMIC_ATTRIBUTE";
export const PROCESS_DYNAMIC_ATTRIBUTE_LOADING = "PROCESS_DYNAMIC_ATTRIBUTE_LOADING";
export const PROCESS_DYNAMIC_ATTRIBUTE_ERROR = "PROCESS_DYNAMIC_ATTRIBUTE_ERROR";
