export const RESET_STATE = "RESET_STATE_HIERARCHY_LEVEL";
export const GET_LIST = "GET_LIST_HIERARCHY_LEVEL";
export const GET_LIST_LOADING = "GET_LIST_LOADING_HIERARCHY_LEVEL";
export const GET_LIST_ERROR = "GET_LIST_ERROR_HIERARCHY_LEVEL";

export const RESET_PROCESS_HIERARCHY_LEVEL = "RESET_PROCESS_HIERARCHY_LEVEL";
export const PROCESS_HIERARCHY_LEVEL = "PROCESS_HIERARCHY_LEVEL";
export const PROCESS_HIERARCHY_LEVEL_LOADING = "PROCESS_HIERARCHY_LEVEL_LOADING";
export const PROCESS_HIERARCHY_LEVEL_ERROR = "PROCESS_HIERARCHY_LEVEL_ERROR";
