export const RESET_STATE_PROCESS_BULK_UPLOAD = "RESET_STATE_PROCESS_BULK_UPLOAD";
export const PROCESS_BULK_UPLOAD = "PROCESS_BULK_UPLOAD";
export const PROCESS_BULK_UPLOAD_LOADING = "PROCESS_LOADING_BULK_UPLOAD";
export const PROCESS_BULK_UPLOAD_ERROR = "PROCESS_ERROR_BULK_UPLOAD";
