export const RESET_STATE = "RESET_STATE_DOCUMENTS_TYPES";
export const GET_LIST = "GET_LIST_DOCUMENTS_TYPES";
export const GET_LIST_LOADING = "GET_LIST_LOADING_DOCUMENTS_TYPES";
export const GET_LIST_ERROR = "GET_LIST_ERROR_DOCUMENTS_TYPES";
export const RESET_STATE_POST_DOCUMENT = "RESET_STATE_POST_DOCUMENT";
export const POST_DOCUMENT_LOADING = "POST_DOCUMENT_LOADING";
export const POST_DOCUMENT = "POST_DOCUMENT";
export const POST_DOCUMENT_ERROR = "POST_DOCUMENT_ERROR";
