export const RESET_STATE = "RESET_STATE_ROLES";
export const GET_LIST = "GET_LIST_ROLES";
export const GET_LIST_LOADING = "GET_LIST_LOADING_ROLES";
export const GET_LIST_ERROR = "GET_LIST_ERROR_ROLES";
