export const RESET_STATE = "RESET_STATE_GENDER";
export const GET_LIST = "GET_LIST_GENDER";
export const GET_LIST_LOADING = "GET_LIST_LOADING_GENDER";
export const GET_LIST_ERROR = "GET_LIST_ERROR_GENDER";
