export const RESET_STATE = "RESET_STATE_COUNTRIES";
export const GET_LIST = "GET_LIST_COUNTRIES";
export const GET_LIST_LOADING = "GET_LIST_LOADING_COUNTRIES";
export const GET_LIST_ERROR = "GET_LIST_ERROR_COUNTRIES";
